
import { Car } from './types';

export const CAR_DATA: Car[] = [
  {
    id: 1,
    make: 'Tesla',
    model: 'Model S',
    year: 2023,
    type: 'Sedan',
    pricePerDay: 150,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Electric',
    imageUrl: 'https://picsum.photos/seed/tesla-s/800/600',
    features: ['Autopilot', 'Panoramic Sunroof', '17" Touchscreen', 'Premium Sound System'],
  },
  {
    id: 2,
    make: 'Porsche',
    model: '911 Carrera',
    year: 2024,
    type: 'Sports Car',
    pricePerDay: 350,
    seats: 4,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    imageUrl: 'https://picsum.photos/seed/porsche-911/800/600',
    features: ['Sport Chrono Package', 'Leather Interior', 'Bose Surround Sound', 'Dynamic Lighting'],
  },
  {
    id: 3,
    make: 'Range Rover',
    model: 'Velar',
    year: 2023,
    type: 'SUV',
    pricePerDay: 180,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Diesel',
    imageUrl: 'https://picsum.photos/seed/range-rover/800/600',
    features: ['All-Wheel Drive', 'Meridian Sound System', 'Sliding Panoramic Roof', 'Heated Seats'],
  },
  {
    id: 4,
    make: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    type: 'Coupe',
    pricePerDay: 280,
    seats: 4,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    imageUrl: 'https://picsum.photos/seed/bmw-m4/800/600',
    features: ['Carbon Fiber Roof', 'M Sport Seats', 'Harman Kardon Audio', 'Adaptive M Suspension'],
  },
  {
    id: 5,
    make: 'Audi',
    model: 'RS7',
    year: 2023,
    type: 'Sportback',
    pricePerDay: 300,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Hybrid',
    imageUrl: 'https://picsum.photos/seed/audi-rs7/800/600',
    features: ['Matrix LED Headlights', 'Virtual Cockpit', 'Bang & Olufsen Sound System', 'Air Suspension'],
  },
  {
    id: 6,
    make: 'Mercedes-Benz',
    model: 'G-Class',
    year: 2023,
    type: 'SUV',
    pricePerDay: 400,
    seats: 5,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    imageUrl: 'https://picsum.photos/seed/g-class/800/600',
    features: ['Burmester Surround Sound', 'Nappa Leather', '3-Zone Climate Control', 'Off-Road Capability'],
  },
  {
    id: 7,
    make: 'Ford',
    model: 'Mustang GT',
    year: 2024,
    type: 'Muscle Car',
    pricePerDay: 120,
    seats: 4,
    transmission: 'Manual',
    fuelType: 'Gasoline',
    imageUrl: 'https://picsum.photos/seed/mustang-gt/800/600',
    features: ['5.0L V8 Engine', 'Digital Instrument Cluster', 'Selectable Drive Modes', 'B&O Sound System'],
  },
  {
    id: 8,
    make: 'Jaguar',
    model: 'F-Type',
    year: 2023,
    type: 'Sports Car',
    pricePerDay: 250,
    seats: 2,
    transmission: 'Automatic',
    fuelType: 'Gasoline',
    imageUrl: 'https://picsum.photos/seed/jaguar-f-type/800/600',
    features: ['Switchable Active Exhaust', 'Pixel LED Headlights', 'Meridian Sound System', 'Performance Seats'],
  },
];
